[env]
TERM = "xterm-256color"

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 14.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "FantasqueSansM Nerd Font Mono"
# family = "DroidSansM Nerd Font"
# family = "FiraCode Nerd Font Mono"
# family = "Cascadia Code"
# family = "Liberation Mono for Powerline"
style = "Regular"

[font.bold]
family = "FantasqueSansM Nerd Font Mono"
# family = "DroidSansM Nerd Font"
# family = "FiraCode Nerd Font Mono"
# family = "Cascadia Code"
# family = "Liberation Mono for Powerline"
# family = "Fantasque Sans Mono"
style = "Bold"

[font.italic]
family = "FantasqueSansM Nerd Font Mono"
# family = "DroidSansM Nerd Font"
# family = "FiraCode Nerd Font Mono"
# family = "Cascadia Code"
# family = "Liberation Mono for Powerline"
# family = "Fantasque Sans Mono"
style = "Regular"
# style = "Italic"

[font.offset]
x = 0
y = 0

[scrolling]
history = 50000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
dynamic_padding = false
dynamic_title = true
opacity = 1.0

[window.dimensions]
columns = 110
lines = 30

[window.padding]
x = 0
y = 0

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"

[general]

live_config_reload = true
# import = ["~/.config/alacritty/solarized_light.toml"]
# import = ["~/.config/alacritty/solarized_dark.toml"]
import = ["~/.config/alacritty/dracula.toml"]

# import = ["~/.config/alacritty/github_light.toml"]
# import = ["~/.config/alacritty/github_dark.toml"]
# import = ["~/.config/alacritty/gruvbox_dark.toml"]
# import = ["~/.config/alacritty/gruvbox_light.toml"]
